movieproject/movieapp/urls.py
from django.contrib import admin
from django.urls import path

from movieapp import views

app_name = "movieapp"

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.home, name="home"),
    path('', views.MovieList.as_view(), name="home"),

    # path('details/<int:p>', views.details, name="details"),
    path('movie/<int:pk>', views.MovieDetail.as_view(), name="details"),

    # path('update/<int:p>', views.update, name="update"),
    path('update/<int:pk>', views.MovieUpdate.as_view(), name="update"),

    # path('delete/<int:p>', views.delete, name="delete"),
    path('delete/<int:pk>', views.Moviedelete.as_view(), name="delete"),


    # path('add', views.add, name="add"),
    path('add', views.Movieadd.as_view(), name="add"),

]

movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),

]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models


# Create your models here.


class Movietb(models.Model):
    name = models.CharField(max_length=20)
    desc = models.TextField()
    year = models.IntegerField(null=True,blank=True)
    image = models.ImageField(upload_to="movies", null=True, blank=True)

    def __str__(self):
        return self.name

movieproject/movieapp/views.py
from django.shortcuts import render
from django.urls import reverse_lazy

from movieapp.models import Movietb

from movieapp.form import movieform
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView


# Create your views here.

# def home(request):
#     m = Movietb.objects.all()
#     return render(request, 'home.html', {'m': m})

class MovieList(ListView):  # ListView displays all objects/records retrieving from a model.
    model = Movietb
    template_name = "home.html"
    context_object_name = "m"


# def details(request, p):
#     m = Movietb.objects.get(id=p)
#     return render(request, 'details.html', {'m': m})


class MovieDetail(DetailView):  # DetailView diaplays a particular object retrieving from model.
    model = Movietb
    template_name = 'details.html'
    context_object_name = "m"


# def add(request):
#     if (request.method == "POST"):
#         form = movieform(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             return home(request)
#
#     form = movieform()
#     return render(request, 'add.html', {'form': form})

class Movieadd(CreateView):  # CreateView displays a form for adding new object and handles form
    model = Movietb
    template_name = "add.html"
    fields = "__all__"
    success_url = reverse_lazy('movieapp:home')


# def update(request, p):
#     m = Movietb.objects.get(id=p)
#     if (request.method == "POST"):
#         form = movieform(request.POST, request.FILES, instance=m)
#         if form.is_valid():
#             form.save()
#             return home(request)
#
#     form = movieform(instance=m)
#     return render(request, 'update.html', {'form': form})

class MovieUpdate(UpdateView):
    model = Movietb
    template_name = "update.html"
    fields = "__all__"
    success_url = reverse_lazy('movieapp:home')


# def delete(request, p):
#     m = Movietb.objects.get(id=p)
#     m.delete()
#     return home(request)


class Moviedelete(DeleteView):
    model = Movietb
    success_url = reverse_lazy('movieapp:home')
    template_name = 'delete.html'

movieproject/templates/add.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<center>
   <h3>Add Movie</h3>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
<!--        <table>-->
<!--            {{form.as_table}}-->
<!--        </table>-->
        <input type="submit">
    </form>
</center>


{% endblock %}

movieproject/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{%  static 'css/style.css' %}">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <div class="container-fluid">
        <a class="navbar-brand text-light" href="#">ONLINE MOVIE STORE</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

      <form class="d-flex">
          <a href="{% url 'movieapp:add' %}" class="btn btn-primary btn-lg active bg-info text-white" >Add Movie</a>

      </form>

  </div>
</nav>

{% block content %}

{% endblock %}
</body>
</html>

movieproject/templates/delete.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}
<center>
   <h3>Update Movie</h3>
    <form method="POST">
        {% csrf_token %}
        <p>
            Are you sure you want to delete???
        </p>
        <input type="submit">
    </form>
</center>


{% endblock %}

movieproject/templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h2>Movie Details</h2>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-5">
            <img src="{{m.image.url}}" height="200px" width="200px">
        </div>
        <div class="col-sm-7">
            <b>{{m.name}}  {{m.year}}</b><br>
            {{m.desc}}<br>

            <a href="{% url 'movieapp:update' m.id %}" class="btn btn-primary">Update</a>
            <a href="{% url 'movieapp:delete' m.id %}" class="btn btn-primary">Delete</a>
        </div>
    </div>
</div>

{% endblock %}

movieproject/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h2>Movie List</h2>
<div class="row">
   {% for i in m %}

    <div class="col-sm-4 mb-5">

        <div class="card" style="width: 18rem; height:650px;">
            <img src="{{i.image.url}}" class="card-img-top" height="286px" width="420px">
          <div class="card-body">
            <h5 class="card-title">{{i.name}} {{i.year}}</h5>
            <p class="card-text">{{i.desc}}</p>

            <a href="{% url 'movieapp:details' i.id %}" class="btn btn-primary">Details</a>
          </div>
        </div>
    </div>

    {% endfor %}

</div>


{% endblock %}

movieproject/templates/update.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<center>
   <h3>Update Movie</h3>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
<!--        <table>-->
<!--            {{form.as_table}}-->
<!--        </table>-->
        <input type="submit">
    </form>
</center>


{% endblock %}